-- Create users table first, as portfolio depends on it
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Create portfolio table, referencing the users table
CREATE TABLE portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE portfolio
ADD CONSTRAINT FK_PORTFOLIO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- Create holding table, referencing the portfolio table
CREATE TABLE holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_id VARCHAR(255) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    portfolio_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE holding
ADD CONSTRAINT FK_HOLDING_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolio (id);
